/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracesIndexRouteImport } from './routes/traces/index'
import { Route as TracesTraceIdRouteImport } from './routes/traces/$traceId'

const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TracesRoute,
} as any)
const TracesTraceIdRoute = TracesTraceIdRouteImport.update({
  id: '/$traceId',
  path: '/$traceId',
  getParentRoute: () => TracesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/traces': typeof TracesRouteWithChildren
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/traces': typeof TracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/traces': typeof TracesRouteWithChildren
  '/traces/$traceId': typeof TracesTraceIdRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/traces' | '/traces/$traceId' | '/traces/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/traces/$traceId' | '/traces'
  id: '__root__' | '/' | '/traces' | '/traces/$traceId' | '/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TracesRoute: typeof TracesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof TracesRoute
    }
    '/traces/$traceId': {
      id: '/traces/$traceId'
      path: '/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof TracesTraceIdRouteImport
      parentRoute: typeof TracesRoute
    }
  }
}

interface TracesRouteChildren {
  TracesTraceIdRoute: typeof TracesTraceIdRoute
  TracesIndexRoute: typeof TracesIndexRoute
}

const TracesRouteChildren: TracesRouteChildren = {
  TracesTraceIdRoute: TracesTraceIdRoute,
  TracesIndexRoute: TracesIndexRoute,
}

const TracesRouteWithChildren =
  TracesRoute._addFileChildren(TracesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TracesRoute: TracesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
